# Generated by Django 5.1 on 2024-08-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
