# Generated by Django 5.1 on 2024-08-28 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0004_remove_order_user_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aibh.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aibh.profile')),
            ],
        ),
    ]
