# Generated by Django 5.1 on 2024-08-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0006_remove_profile_is_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PAID', 'Payé'), ('PENDING', 'En cours'), ('UNPAID', 'Non payé')], default='UNPAID', max_length=7, null=True),
        ),
    ]
