# Generated by Django 5.1 on 2024-08-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0007_panier_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=10)),
                ('transaction_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aibh.panier')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aibh.profile')),
            ],
        ),
    ]
