# Generated by Django 5.1 on 2024-08-29 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0009_affiliatelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='affiliate_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aibh.affiliatelink'),
        ),
    ]
