# Generated by Django 5.1 on 2024-08-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0010_panier_affiliate_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='token',
            field=models.CharField(default=1, editable=False, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
