# Generated by Django 5.1 on 2024-08-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0011_affiliatelink_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='product',
        ),
        migrations.AddField(
            model_name='panier',
            name='product',
            field=models.ManyToManyField(to='aibh.product'),
        ),
    ]
