# Generated by Django 5.1 on 2024-08-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0013_remove_panier_product_panier_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='payment_method',
        ),
    ]
