# Generated by Django 5.1 on 2024-08-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0014_remove_achat_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='payment_status',
        ),
    ]
