# Generated by Django 5.1 on 2024-08-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0015_remove_achat_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='payment_method',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achat',
            name='payment_status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
