# Generated by Django 5.1 on 2024-08-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0016_achat_payment_method_achat_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
