# Generated by Django 5.1 on 2024-08-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0017_product_margin_product_shipping_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='margin',
            new_name='marge',
        ),
    ]
