# Generated by Django 5.1 on 2024-08-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibh', '0018_rename_margin_product_marge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_fee',
        ),
        migrations.AddField(
            model_name='product',
            name='prix_livraison',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
